// Code generated by hertz generator.

package asset_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _insertassetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryassetMw() []app.HandlerFunc {
	// your code...
	return nil
}
