// Code generated by Kitex v0.5.2. DO NOT EDIT.

package assetmanagement

import (
	server "github.com/cloudwego/kitex/server"
	asset_management "orbital_poc/hertz_server/kitex_gen/asset_management"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler asset_management.AssetManagement, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
